const keywords = [
    { name: "四红", type:"红发", keyword:[/四红/, /全红/] },
    { name: "五红", type:"红发", keyword:[/五红/, /全红/] },
    { name: "六红", type:"红发", keyword:[/六红/, /全红/] },
    { name: "七红", type:"红发", keyword:[/七红/, /全红/] },
    { name: "八红", type:"红发", keyword:[/八红/, /全红/] },
    { name: "九红", type:"红发", keyword:[/九红/, /全红/] },
    { name: "十红", type:"红发", keyword:[/十红/, /全红/] },
    { name: "猴红", type:"红发", keyword:[/猴红/, /全红/] },
    { name: "叽红", type:"红发", keyword:[/叽红/, /鸡红/, /全红/] },
    { name: "羊红", type:"红发", keyword:[/羊红/, /全红/] },
    { name: "猪红", type:"红发", keyword:[/猪红/, /全红/] },
    { name: "狗红", type:"红发", keyword:[/狗红/, /全红/] },
    { name: "狐金", type:"金发", keyword:[/狐金/, /全金/, /三巨头/] },
    { name: "一代金", type:"金发", keyword:[/一代金/, /全金/, /三巨头/] },
    { name: "苏金", type:"金发", keyword:[/苏金/, /全金/, /三巨头/] },
    { name: "猴金", type:"金发", keyword:[/猴金/, /全金/, /三巨头/] },
    { name: "蝶金", type:"金发", keyword:[/蝶金/, /全金/] },
    { name: "喵金", type:"金发", keyword:[/喵金/, /全金/] },
    { name: "考金", type:"金发", keyword:[/考金/, /全金/] },
    { name: "鸡金", type:"金发", keyword:[/鸡金/, /叽金/, /全金/] },
    { name: "国金", type:"金发", keyword:[/国金/, /全金/] },
    { name: "倒闭金", type:"金发", keyword:[/倒闭金/, /全金/] },
    { name: "狗金", type:"金发", keyword:[/狗金/, /全金/] },
    { name: "端午金", type:"金发", keyword:[/端午金/, /龙女金/, /全金/] },
    { name: "珊瑚金", type:"金发", keyword:[/珊瑚金/, /全金/] },
    { name: "中秋金", type:"金发", keyword:[/中秋金/, /全金/] },
    { name: "玫瑰金", type:"金发", keyword:[/玫瑰金/, /全金/] },
    { name: "猪金", type:"金发", keyword:[/猪金/, /全金/] },
    { name: "兔金", type:"金发", keyword:[/兔金/, /全金/] },
    { name: "丝路金", type:"金发", keyword:[/丝路金/, /全金/] },
    { name: "粉白菜", type:"五限", keyword:[/粉白菜/, /双色?白菜/] },
    { name: "紫白菜", type:"五限", keyword:[/紫白菜/, /双色?白菜/] },
    { name: "黑金夜斩白", type:"五限", keyword:[/黑金夜斩白/, /双色?夜斩白/] },
    { name: "白金夜斩白", type:"五限", keyword:[/白金夜斩白/, /双色?夜斩白/] },
    { name: "情阅", type:"五限", keyword:[/情阅/, /贺华岁/] },
    { name: "谷雨", type:"五限", keyword:[/谷雨/, /贺华岁/] },
    { name: "白螺母", type:"五限", keyword:[/白螺母/, /双色?螺母/] },
    { name: "蓝螺母", type:"五限", keyword:[/蓝螺母/, /双色?螺母/] },
    { name: "红墨韵", type:"五限", keyword:[/红墨韵/, /双色?墨韵/] },
    { name: "黑墨韵", type:"五限", keyword:[/黑墨韵/, /双色?墨韵/] },
    { name: "红彩云", type:"五限", keyword:[/红彩云/, /双色?彩云/] },
    { name: "蓝彩云", type:"五限", keyword:[/蓝彩云/, /双色?彩云/] },
    { name: "红风露", type:"五限", keyword:[/红风露/, /双色?风露/] },
    { name: "蓝风露", type:"五限", keyword:[/黑风露/, /蓝风露/, /双色?风露/] },
    { name: "橙繁", type:"五限", keyword:[/橙繁/, /双色?繁/] },
    { name: "粉繁", type:"五限", keyword:[/粉繁/, /双色?繁/] },
    { name: "阳春海", type:"五限", keyword:[/阳春海/, /双色?阳春/] },
    { name: "阳春冰", type:"五限", keyword:[/阳春冰/, /双色?阳春/] },
    { name: "红玉蟒", type:"五限", keyword:[/红玉蟒/, /玉蟒珥/, /双色?玉蟒/] },
    { name: "黑玉蟒", type:"五限", keyword:[/黑玉蟒/, /玉蟒鲜/, /双色?玉蟒/] },
    { name: "红捕风", type:"五限", keyword:[/红捕风/, /双色?捕风/] },
    { name: "黑捕风", type:"五限", keyword:[/黑捕风/, /紫捕风/, /双色?捕风/] },
    { name: "红紧那", type:"五限", keyword:[/红紧那/, /双色?紧那/] },
    { name: "黑紧那", type:"五限", keyword:[/黑紧那/, /紫紧那/, /双色?紧那/] },
    { name: "紫火舞", type:"五限", keyword:[/紫火舞/, /双色?火舞/, /火舞杏甜/] },
    { name: "白火舞", type:"五限", keyword:[/白火舞/, /双色?火舞/, /火舞未翔/] },
    { name: "蓝花开", type:"五限", keyword:[/蓝花开/, /双色?花开/] },
    { name: "黄花开", type:"五限", keyword:[/黄花开/, /双色?花开/] },
    { name: "策马若如", type:"五限", keyword:[/策马若如/, /双色?策马/] },
    { name: "策马河洲", type:"五限", keyword:[/策马河洲/, /双色?策马/] },
    { name: "黑风华", type:"五限", keyword:[/黑风华/, /双色?风华/] },
    { name: "紫风华", type:"五限", keyword:[/紫风华/, /双色?风华/] },
    { name: "白娃娃", type:"六限", keyword:[/白娃娃/, /四色娃娃/] },
    { name: "粉娃娃", type:"六限", keyword:[/粉娃娃/, /四色娃娃/] },
    { name: "黄娃娃", type:"六限", keyword:[/黄娃娃/, /四色娃娃/] },
    { name: "蓝娃娃", type:"六限", keyword:[/蓝娃娃/, /四色娃娃/] },
    { name: "蓝不期", type:"六限", keyword:[/蓝不期/, /双色?不期/] },
    { name: "绿不期", type:"六限", keyword:[/绿不期/, /双色?不期/] },
    { name: "蓝公主", type:"六限", keyword:[/蓝公主/, /双色?公主/] },
    { name: "粉公主", type:"六限", keyword:[/粉公主/, /双色?公主/] },
    { name: "黑年轮", type:"六限", keyword:[/黑年轮/, /四色年轮/] },
    { name: "红年轮", type:"六限", keyword:[/红年轮/, /四色年轮/] },
    { name: "蓝年轮", type:"六限", keyword:[/蓝年轮/, /四色年轮/] },
    { name: "黄年轮", type:"六限", keyword:[/黄年轮/, /四色年轮/] },
    { name: "粉人面", type:"六限", keyword:[/粉人面/, /双色?人面/] },
    { name: "蓝人面", type:"六限", keyword:[/蓝人面/, /双色?人面/] },
    { name: "黄无色", type:"六限", keyword:[/黄无色/, /四色无色/] },
    { name: "蓝无色", type:"六限", keyword:[/蓝无色/, /四色无色/] },
    { name: "粉无色", type:"六限", keyword:[/粉无色/, /四色无色/] },
    { name: "白无色", type:"六限", keyword:[/白无色/, /四色无色/] },
    { name: "红九曲", type:"六限", keyword:[/红九曲/, /双色?九曲/] },
    { name: "蓝九曲", type:"六限", keyword:[/蓝九曲/, /双色?九曲/] },
    { name: "金陵", type:"六限", keyword:[/金陵/] },
    { name: "兰亭", type:"其他", keyword:[/兰亭/] },
    { name: "九壤", type:"其他", keyword:[/九壤/] },
    { name: "禹梦", type:"其他", keyword:[/禹梦/] },
    { name: "长天", type:"其他", keyword:[/长天/] },
    { name: "沐云飞", type:"其他", keyword:[/沐云飞/] },
    { name: "红舞步", type:"其他", keyword:[/红舞步/, /舞步/] },
    { name: "封川", type:"其他", keyword:[/封川/] },
    { name: "水云寒", type:"其他", keyword:[/水云寒/] },
    { name: "微草", type:"其他", keyword:[/微草/] },
    { name: "清宵重天", type:"其他", keyword:[/清宵重天/] },
    { name: "暮归锦夜", type:"其他", keyword:[/暮归锦夜/] },
    { name: "霆螭", type:"其他", keyword:[/霆螭/] },
    { name: "踏月", type:"其他", keyword:[/踏月/] },
    { name: "寒梅", type:"其他", keyword:[/寒梅/] },
    { name: "一代黑", type:"披风", keyword:[/一代黑/] },
    { name: "一代白", type:"披风", keyword:[/一代白/] },
    { name: "一代紫", type:"披风", keyword:[/一代紫/] },
    { name: "一代黄", type:"披风", keyword:[/一代黄/] },
    { name: "一代红", type:"披风", keyword:[/一代红/] },
    { name: "一代粉", type:"披风", keyword:[/一代粉/] },
    { name: "二代黑", type:"披风", keyword:[/二代黑/] },
    { name: "栽火莲", type:"披风", keyword:[/栽火莲/] },
    { name: "六翼", type:"披风", keyword:[/六翼/, /6e/] },
    { name: "情人枕", type:"披风", keyword:[/情人枕/, /情R枕/] },
    { name: "鸡翅膀", type:"披风", keyword:[/狄仁杰披风/, /鸡翅膀/] },
    { name: "羽毛", type:"披风", keyword:[/羽毛/] },
    { name: "星空", type:"披风", keyword:[/星空/] },
    { name: "阵营蓝", type:"披风", keyword:[/阵营蓝/] },
    { name: "阵营红", type:"披风", keyword:[/阵营红/] },
    { name: "狐狸毛", type:"披风", keyword:[/狐狸毛/] },
    { name: "孔雀", type:"披风", keyword:[/孔雀/] },
  //  { name: "周年龙", type:"披风", keyword:[/周年龙/] },
  //  { name: "周年粉", type:"披风", keyword:[/周年粉/] },
    { name: "狼头", type:"披风", keyword:[/狼头/] },
    { name: "天辉", type:"披风", keyword:[/天辉/] },
    { name: "白莲花", type:"披风", keyword:[/白莲花/] },
    { name: "羽毛", type:"披风", keyword:[/羽毛/] },
    { name: "画卷", type:"披风", keyword:[/画卷/] },
    { name: "喵萝干", type:"披风", keyword:[/喵萝干/] },
    { name: "毒萝干", type:"披风", keyword:[/毒萝干/] },
    { name: "双十一", type:"披风", keyword:[/双十一/] },
    { name: "黑盒", type:"礼盒", keyword:[/黑盒/] },
    { name: "蓝盒", type:"礼盒", keyword:[/蓝盒/] },
    { name: "红盒", type:"礼盒", keyword:[/红盒/] },
    { name: "青盒", type:"礼盒", keyword:[/青盒/] },
    { name: "糖盒", type:"礼盒", keyword:[/糖盒/] },
    { name: "白盒", type:"礼盒", keyword:[/白盒/] },
    { name: "喵盒", type:"礼盒", keyword:[/喵盒/] },
    { name: "刀盒", type:"礼盒", keyword:[/刀盒/, /貂盒/] },
    { name: "粉盒", type:"礼盒", keyword:[/粉盒/] },
    { name: "花盒", type:"礼盒", keyword:[/花盒/] },
    { name: "叽盒", type:"礼盒", keyword:[/叽盒/] },
    { name: "秃盒", type:"礼盒", keyword:[/秃盒/] },
    { name: "伞盒", type:"礼盒", keyword:[/蓬莱盒/, /伞盒/] },
    { name: "猪盒", type:"礼盒", keyword:[/猪盒/] },
    { name: "毒盒", type:"礼盒", keyword:[/毒盒/] },
    { name: "狗盒", type:"礼盒", keyword:[/狗盒/] },
    { name: "歌盒", type:"礼盒", keyword:[/歌盒/] },
    { name: "一代七夕", type:"礼盒", keyword:[/一代七夕/] },
    { name: "二代七夕", type:"礼盒", keyword:[/二代七夕/] },
    { name: "三代七夕", type:"礼盒", keyword:[/三代七夕/] },
    { name: "四代七夕", type:"礼盒", keyword:[/四代七夕/] },
    { name: "一代重阳", type:"礼盒", keyword:[/一代重阳/] },
    { name: "二代重阳", type:"礼盒", keyword:[/二代重阳/] },
    { name: "黑端午", type:"礼盒", keyword:[/黑端午/] },
    { name: "白端午", type:"礼盒", keyword:[/白端午/] },
    { name: "狄仁杰", type:"礼盒", keyword:[/狄仁杰/] },
    { name: "中秋盒", type:"礼盒", keyword:[/中秋盒/] },
    { name: "丝路盒", type:"礼盒", keyword:[/丝路盒/] },
    { name: "一代元宵", type:"礼盒", keyword:[/一代元宵/] },
    { name: "二代元宵", type:"礼盒", keyword:[/二代元宵/] },
    { name: "蓝中秋", type:"礼盒", keyword:[/蓝中秋/] },
    { name: "粉中秋", type:"礼盒", keyword:[/(?!代)粉中秋/] },
    { name: "绿中秋", type:"礼盒", keyword:[/绿中秋/] },
    { name: "花朝盒", type:"礼盒", keyword:[/花朝/] },
    { name: "狗盒子", type:"礼盒", keyword:[/狗盒子/] },
    { name: "猫盒子", type:"礼盒", keyword:[/猫盒子/] },
    { name: "棉袄", type:"礼盒", keyword:[/棉袄/] },
    { name: "泠月兰芳", type:"礼盒", keyword:[/泠月兰芳/] },
    { name: "踏云盒子", type:"礼盒", keyword:[/踏云/] },
    { name: "飞天盒子", type:"礼盒", keyword:[/飞天/] },
    { name: "四代粉中秋", type:"礼盒", keyword:[/四代粉中秋/] },
    { name: "100cw", type:"杂项", keyword:[/100cw/] },
    { name: "大铁", type:"杂项", keyword:[/大铁/] },
    { name: "滚滚", type:"杂项", keyword:[/滚滚/] },
    { name: "月伴", type:"杂项", keyword:[/月伴/] },
    { name: "焰归", type:"杂项", keyword:[/焰归/] },
  //  { name: "珠盏", type:"杂项", keyword:[/珠盏/] },
    { name: "夜话", type:"杂项", keyword:[/夜话/] },
    { name: "黑龙", type:"杂项", keyword:[/黑龙/] },
    { name: "赤兔", type:"杂项", keyword:[/赤兔/] },
    { name: "二内", type:"杂项", keyword:[/二内/] },
    { name: "月伴晨星", type:"杂项", keyword:[/月伴晨星/] },
    { name: "黄金船", type:"杂项", keyword:[/土豪船/, /黄金船/, /星河清梦/] },
    { name: "霸红尘", type:"杂项", keyword:[/霸红尘/] },
    { name: "赤兔", type:"杂项", keyword:[/赤兔/] },
    { name: "三山四海", type:"杂项", keyword:[/三山/] },
    { name: "三尺青锋", type:"杂项", keyword:[/三尺/] },
    { name: "九天逍遥散", type:"杂项", keyword:[/九天逍遥/] },
    { name: "大侠", type:"杂项", keyword:[/大侠/] },
    { name: "阴阳两界", type:"杂项", keyword:[/阴阳两界/, /霸红尘/] },
    { name: "黑白路", type:"杂项", keyword:[/黑白路/, /大宝剑/] },
    { name: "大雕", type:"杂项", keyword:[/大雕/] },
    { name: "团团", type:"杂项", keyword:[/团团/] },
    { name: "闹闹", type:"杂项", keyword:[/闹闹/] },
    { name: "鹦鹉", type:"杂项", keyword:[/鹦鹉/] },
    { name: "橘猫", type:"杂项", keyword:[/橘猫/, /橘胖/] },
    { name: "萝莉", type:"体型", keyword:[/萝莉/, /咩萝/, /秀萝/, /花萝/, /毒萝(?!干)/, /琴萝/, /鸽萝/, /喵萝(?!干)/, /军萝/, /盾萝/, /伞萝/, /叽萝/, /鸡萝/, /炮萝/, /丐萝/, /刀萝/]},
    { name: "成女", type:"体型", keyword:[/成女/, /道姑/, /秀姐/, /花姐/, /毒姐/, /琴姐/, /琴娘/, /喵姐/, /军娘/, /盾娘/, /伞娘/, /二小姐/, /炮姐/, /丐姐/, /刀娘/, /雪萝/]},
    { name: "成男", type:"体型", keyword:[/成男/, /道长/, /花哥/, /毒哥/, /琴爹/, /喵哥/, /军爷/, /苍爹/, /伞爹/, /二少/, /炮哥/, /丐哥/, /刀哥/, /大师/, /刀爷/, /刀爹/, /雪爹/]},
    { name: "正太", type:"体型", keyword:[/正太/, /咩太/, /花太/, /秀太/, /毒太/, /呱太/, /琴太/, /喵太/, /军太/, /盾太/, /伞太/, /叽太/, /炮太/, /丐太/, /刀太/, /秃太/, /雪娘/, /小和尚/]},
]

const schools = ['五毒', '七秀', '万花', '长歌', '天策', '藏剑', '少林', '丐帮', '苍云', '纯阳', '明教', '唐门', '霸刀', '蓬莱', '凌雪阁']
const schoolKeyword = [
    { name :'五毒', keywords: ["毒萝", "毒姐", "毒哥", "毒太", "呱太"] },
    { name :'七秀', keywords: ["秀萝", "秀太", "秀姐"] },
    { name :'万花', keywords: ["花萝", "花姐", "花哥", "花太"] },
    { name :'长歌', keywords: ["琴萝", "琴姐", "琴爹", "琴太", "鸽萝", "琴娘"] },
    { name :'天策', keywords: ["军萝", "军娘", "军爷", "军太"] },
    { name :'藏剑', keywords: ["叽萝", "二小姐","鸡萝", "二少", "叽太"] },
    { name :'少林', keywords: ["大师", "秃太", "小和尚"] },
    { name :'丐帮', keywords: ["丐萝", "丐姐", "丐哥", "丐太"] },
    { name :'苍云', keywords: ["盾萝", "盾娘", "苍爹", "盾太"] },
    { name :'纯阳', keywords: ["咩萝", "道姑", "道长", "咩太"] },
    { name :'明教', keywords: ["喵萝", "喵姐", "喵哥", "喵太"] },
    { name :'唐门', keywords: ["炮萝", "炮姐", "炮哥", "炮太"] },
    { name :'霸刀', keywords: ["刀萝", "刀娘", "刀哥", "刀太", "刀爷", "刀爹"] },
    { name :'蓬莱', keywords: ["伞萝", "伞娘", "伞爹", "伞太"] },
    { name :'凌雪阁', keywords: ["雪萝", "雪爹", "雪娘"] },
]

module.exports = {
    keywords,
    schools,
    schoolKeyword,
}